[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://images.unsplash.com/.*"]

[build]
  command = "npm run build"
  publish = "dist/skloniste/browser"
